name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.repository == 'timdeschryver/ngrx-immer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: install
        run: npm install
      - name: build
        run: npm run dist:build
      - name: test
        run: npm run test
      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npx semantic-release